### ISSUE TITLE
Consider adding Elasticsearch

### ISSUE THREAD

**Issue by kkomelin** [wodby/docker4php#1]
Hi guys,

Thank you for your hard work on all your Docker projects. 
Could you please consider adding Elasticsearch to docker4php stack?

For example, you could use the code from the following project which includes Elasticsearch https://github.com/laradock/laradock
https://github.com/laradock/laradock/tree/master/elasticsearch

Thank you so much,
Konstantin

**Comment by csandanov** [comment]
Thank you for the request,  [wodby/elasticsearch](https://github.com/wodby/elasticsearch) and [wodby/kibana](https://github.com/wodby/kibana/) images (alpine-based) have been added. Available only in master for now.

**Comment by kkomelin** [comment]
@csandanov Thank you very much Chingis. It's a great New Year's gift to the community.
Happy Holidays, guys! May the New Year bring success to Wodby and lots of joy to you and your families!

**Comment by csandanov** [comment]
Added with [1.1.0](https://github.com/wodby/docker4php/releases/tag/1.1.0) release

**Comment by kkomelin** [comment]
@csandanov Awesome. Thanks.
