### ISSUE TITLE
Cannot get Mutagen to work on 

### ISSUE THREAD

**Issue by abdullah10182** [wodby/docker4php#14]
I'm trying to follow the steps on how to use Mutagen, but on step 3 i run 

`docker-compose up -d mutagen` 

but I get "No such service: mutagen".

Not sure what I'm doing wrong. Previously I had docker-sync running without any issue.

Any help would be appreciated.

**Comment by csandanov** [comment]
Oh, my bad, I forgot to copy the mutagen service, now added https://github.com/wodby/docker4php/blob/master/docker-compose.yml#L252-L259

**Comment by abdullah10182** [comment]
Thanks for answering.

I had to comment out the init option, otherwise it did not work.
