### ISSUE TITLE
Latest 4.49.1 dev image cannot install php extentions

### ISSUE THREAD

**Issue by beertje44** [wodby/docker4php#21]
`STEP 6/7: RUN docker-php-ext-install gettext
/usr/local/bin/docker-php-ext-install: cd: line 19: can't cd to /usr/src/php/ext: No such file or directory
Error: building at STEP "RUN docker-php-ext-install gettext": while running runtime: exit status 2`

With 8.3-dev-4.48.0 everything builds just fine.

Could it be dev files are missing from the dev image?

**Comment by csandanov** [comment]
Hi, sorry, this is indeed a bug, [fixed now](https://github.com/wodby/php/commit/3fe0cd54eed422d7c00fe3122b9e15e5733491c1) in 4.49.2
