### ISSUE TITLE
Some problems upon working with Laravel

### ISSUE THREAD

**Issue by roman-yakimkin** [wodby/docker4php#3]
Hello.
I'm a novice in docker. 
I need to work with Laravel using docker-compose and I decided to use this solution. I managed to set up containers and install Laravel.
But I encountered some problems. 
1. An error. "The stream or file "laravel.log" could not be opened: failed to open stream: Permission denied". I don't know how to solve it correctly without forcibly setting rights as 777. 
2. Could you clarify me, how can I get into the running container via my terminal? I mean I need to type "php -v" or "php artisan" in my terminal and it should work correctly. How can I do it?

**Comment by csandanov** [comment]
Hi, 

1. what's the location of `laravel.log`, is it created by Laravel? 
2. run `make shell` if you have Makefile or `docker exec -ti [PHP CONTAINER ID] sh`

**Comment by alsar** [comment]
@roman-yakimkin you should set the `PHP_FPM_USER` and `PHP_FPM_GROUP`environment variables for the `php` container to `wodby` so that FPM has write access.

**Comment by csandanov** [comment]
yes, that's one of the options, less secure but totally fine for the local development

**Comment by alsar** [comment]
What do you propose for the production environment?

**Comment by csandanov** [comment]
Have this file owned by `www-data` so FPM could write to it or owned by `wodby` and have `www-data` group with group writing permissions.
